chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login_view'),
    path('register', views.register_view, name='register_view'),
    path('log_out', views.log_out, name='log_out'),
    path('room_view/<int:pk>', views.room_view, name='room_view'),
    path('room_add', views.room_add, name='room_add'),
    path('room_private_view/<int:user_pk>', views.room_private_view, name='room_private_view'),
    path('profile_view', views.profile_view, name='profile_view'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('chat.urls')),  # points to urls file in our `chat` app
    path('admin/', admin.site.urls),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save

class Room(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    is_private = models.BooleanField(default=False)
    name = models.CharField(max_length=100, default=None, null=True)
    updated = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(User, related_name='room_to_user')


class Message(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='message_to_room')
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='message_to_user')

class Profile(models.Model):
    name = models.CharField(max_length=100, default="Anonymous")
    image = models.ImageField(
        default='marina.jpg',
        upload_to='profile_pics'
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


def __create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()


post_save.connect(__create_profile, sender=User)

chat/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django import forms

from . import models

class RoomAddForm(forms.Form):
    name = forms.CharField(label="Group name", required=True)

    def __init__(self, *args, **kwargs):
        # this will throw an exception if the class was initialized without "user_list" argument
        self.user_list = kwargs.pop('user_list')
        super(RoomAddForm, self).__init__(*args, **kwargs)

        # we are initializing this field here because we are using data passed from view: user_list
        self.fields['room_members'] = forms.ModelMultipleChoiceField(
            queryset=self.user_list,
            required=True,
            widget=forms.CheckboxSelectMultiple
        )

        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Row(
                Column('name')
            ),
            Row(
                Column('room_members')
            ),
            Submit('submit', 'Create')
        )

class UserNameChangeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name',
            Submit('user_name_change', 'Change')
        )

    class Meta:
        model = models.Profile
        fields = ['name']


class ImageUploadForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'image',
            Submit('image_upload', 'Upload')
        )

    class Meta:
        model = models.Profile
        fields = ['image']

chat/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from chat import forms, models, serializers


def index(request):
    user = request.user
    if user.is_authenticated:
        room_list = models.Room.objects.filter(users__pk=user.pk).exclude(is_private=True).order_by('-updated')
        user_list = User.objects.exclude(pk=request.user.pk)
        return render(request, 'chat/index.html', {
            'room_list': room_list,
            'user_list': user_list
        })
    else:
        return redirect('chat:login_view')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('chat:index')
        else:
            return render(request, 'chat/login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'chat/login.html', {'form': form})


def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('chat:profile_view')
        else:
            return render(request, 'chat/register.html', {'form': form})
    else:
        return render(request, 'chat/register.html', {'form': UserCreationForm()})


def log_out(request):
    logout(request)

    return redirect('chat:login_view')


def room_view(request, pk):
    user_current = request.user
    if models.Room.objects.filter(pk=pk, users=user_current).exists():
        messages_in_room = models.Message.objects.filter(room=pk)
        messages_in_room_serialized = serializers.MessageSerializer(messages_in_room, many=True).data
        return render(request, 'chat/room.html', {
            'messages': messages_in_room_serialized,
            'room_pk': pk
        })
    else:
        return redirect('chat:index')



def room_add(request):
    user_current = request.user
    user_list = User.objects.exclude(pk=user_current.pk)
    if request.method == 'POST':
        form = forms.RoomAddForm(request.POST, user_list=user_list)
        if form.is_valid():
            room_name = request.POST['name']
            room_users = request.POST.getlist('room_members')
            room_new = models.Room(name=room_name)
            room_new.save()
            room_new.users.add(user_current)
            for user_pk in room_users:
                room_new.users.add(user_pk)
            return redirect('chat:index')
        else:
            return render(request, 'chat/room_add.html', {'form': form})
    else:
        form = forms.RoomAddForm(user_list=user_list)
        return render(request, 'chat/room_add.html', {'form': form})


def room_private_view(request, user_pk):
    user_current = request.user
    user_contact = models.User.objects.get(pk=user_pk)

    room_existing = models.Room.objects.filter(users=user_current, is_private=True).filter(users=user_contact).first()

    if room_existing is not None:
        return redirect('chat:room_view', pk=room_existing.pk)
    else:
        room_new = models.Room(
            is_private=True
        )
        room_new.save()

        room_new.users.add(user_current.pk)
        room_new.users.add(user_contact.pk)

        return redirect('chat:room_view', pk=room_new.pk)


def profile_view(request):
    if request.method == 'POST':
        profile = models.Profile.objects.get(user=request.user)

        if 'image_upload' in request.POST:
            form_image_upload = forms.ImageUploadForm(request.POST, request.FILES, instance=profile)

            if form_image_upload.is_valid():
                form_image_upload.save()

                return render(request, 'chat/profile.html', {
                    'form_image_upload': form_image_upload,
                    'form_user_name_change': forms.UserNameChangeForm(instance=profile)
                })

        elif 'user_name_change' in request.POST:
            form_user_name_change = forms.UserNameChangeForm(request.POST, instance=profile)

            if form_user_name_change.is_valid():
                form_user_name_change.save()

                return render(request, 'chat/profile.html', {
                    'form_image_upload': forms.ImageUploadForm(instance=profile),
                    'form_user_name_change': forms.UserNameChangeForm(instance=profile)
                })

    else:
        profile = models.Profile.objects.get(user=request.user)

        form_image_upload = forms.ImageUploadForm(instance=profile)
        form_user_name_change = forms.UserNameChangeForm(instance=profile)

    return render(request, 'chat/profile.html', {
        'form_image_upload': form_image_upload,
        'form_user_name_change': form_user_name_change
    })

chat/templates/chat/index.html
{% extends 'base.html' %}

{% block content %}

  <div>
    <h1>Main page</h1>
    <form action="http://127.0.0.1:8000/profile_view">
    <input type="submit" value="Profile Page" />
</form>

    <div>
      <form
          action="{% url 'chat:log_out' %}"
          method="post"
      >
        {% csrf_token %}

        <button
            class="btn btn-primary"
            type="submit"
        >
          Log out
        </button>
      </form>
    </div>

    <div>
      <h2>Contacts</h2>

      {% for user in user_list %}
      <a href="{% url 'chat:room_private_view' user_pk=user.pk %}">
        <div>
          {{ user.username }} ({{ user.pk }})
        </div>
      </a>
      {% endfor %}
    </div>

    <div>
      <h2>Group chats</h2>

      <div style="padding: 8px;">
        {% for room in room_list %}
        <a href="{% url 'chat:room_view' pk=room.pk %}">
          <div>
            {{ room.name }} ({{ room.pk }})
          </div>
        {% endfor %}
        </div>

      <div style="padding: 8px;">
        {# We are using form here but GET method, this works the same was as <a href> - just a link to a new URL #}
        <form
            action="{% url 'chat:room_add' %}"
            method="get"
        >
          <button type="submit">
            Create room
          </button>
        </form>
        </div>

    </div>

  </div>

  </div>

{% endblock content %}

chat/templates/chat/login.html
{% extends 'base.html' %}

{% block content %}

  <div style="left: 50%; position: absolute; top: 50%; transform: translate(-50%, -50%)">
    <h1>Log in</h1>

    {% load crispy_forms_tags %} {#  need to load this before the form (part of django-crispy-forms)  #}

    <form method="POST">
      {% csrf_token %}

      {{ form|crispy }}
      {# using template variable "form" and passing it through filter called crispy (part of django-crispy-forms) #}

      <button type="submit">
        Login
      </button>
    </form>

    <div>
      If you do not have an account, <a href="/register">register</a> instead.
    </div>
  </div>

{% endblock content %}

chat/templates/chat/profile.html
<!-- chat/templates/chat/profile.html -->

{% extends 'base.html' %}

{% block content %}

  <div>
    <h1>Profile</h1>
    <form action="http://127.0.0.1:8000">
    <input type="submit" value="Back to Main Page" />
</form>

    <div>
      <div>
        <h2>{{ user.username }}</h2>
      </div>

      <img
          src="{{ user.profile.image.url }}"
          style="width: 200px; height: 200px;"
          alt="Profile image"
      >

      {% load crispy_forms_tags %}
      {% crispy form_image_upload %}
      {% crispy form_user_name_change %}
    </div>
  </div>

{% endblock content %}

chat/templates/chat/register.html
{% extends 'base.html' %}

{% block content %}

  <div style="left: 50%; position: absolute; top: 50%; transform: translate(-50%, -50%)">
    <h1>Register</h1>

    {% load crispy_forms_tags %}
    <form method="POST">
      {% csrf_token %}

      {{ form|crispy }}

      <button type="submit">
        Register
      </button>
    </form>

    <div>
      If you already have an account, <a href="/login">login</a> instead.
    </div>
  </div>

{% endblock content %}

chat/templates/chat/room.html
{% extends 'base.html' %}

{% block content %}

  <div>
    <div id="chat-log" style="padding: 32px"></div>

    <input id="chat-message-input" type="text" size="100"><br>

    <input id="chat-message-submit" type="button" value="Send">

    {{ room_pk|json_script:'room_pk' }}
    {{ messages|json_script:'messages' }}

    <script>

      showExistingMessages()

      const chatSocket = configureChatWebSocket()

      // We are focusing on the text input field as soon as the page is opened (placing caret, so we can start typing)
      document.querySelector('#chat-message-input').focus()

      // Allow to press "enter" button in addition to clicking the "submit" button
      document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
          document.querySelector('#chat-message-submit').click()
        }
      }

      // Here we are handling submit event (press enter or click on the "submit" button
      // We will send the message to our WebSocket, it will in return pass it to our server
      document.querySelector('#chat-message-submit').onclick = function() {
        const messageInputDom = document.querySelector('#chat-message-input')
        const message = messageInputDom.value

        chatSocket.send(JSON.stringify({
          'message': message
        }))

        // We are clearing the text input field after the message is submitted
        messageInputDom.value = ''
      }

      // Here we are creating HTML element for our message and appending it to the main container
      function createMessageNode(message, mainContainer) {
        const messageContainer = document.createElement('div')

        messageContainer.textContent = formatMessage(message)
        messageContainer.style.margin = '8px'
        messageContainer.style.padding = '8px'

        mainContainer.appendChild(messageContainer)
        mainContainer.appendChild(document.createElement('br'))
      }

      function formatMessage(message) {
      if (typeof message === 'string') {
        return `${message}\n`
      } else {
        const dateFormatted = new Intl.DateTimeFormat('ru', {
          hour:   'numeric',
          minute: 'numeric'
        })
          .format(new Date(message.created))

        return `${message.user.username} ${dateFormatted}: ${message.text}\n`
      }
    }

       function configureChatWebSocket() {
        const roomPK = JSON.parse(document.getElementById('room_pk').textContent)

        const chatSocket = new WebSocket(`ws://${window.location.host}/ws/chat/${roomPK}`)

        chatSocket.onmessage = function(event) {
          const data = JSON.parse(event.data)
          const message = data.message

          const mainContainer = document.querySelector('#chat-log')

          createMessageNode(message, mainContainer)
        }

        chatSocket.onclose = function() {
          console.error('Chat socket closed unexpectedly')
        }

        return chatSocket
      }

      function showExistingMessages() {
        const mainContainer = document.querySelector('#chat-log')
        const messages = JSON.parse(document.getElementById('messages').textContent)

        messages.forEach(message => createMessageNode(message, mainContainer))
      }

    </script>

  </div>

{% endblock content %}

chat/templates/chat/room_add.html
{% extends 'base.html' %}

{% block content %}

  <div>
    <h2>Create room</h2>

    {% load crispy_forms_tags %}
    {% crispy form %}
  </div>

{% endblock content %}